dist: xenial
sudo: required

language: go
go_import_path: github.com/src-d/engine

services:
  - docker

stages:
  - name: tests
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: tests
      name: 'Integration Tests Linux 1.10'
      go:
        - 1.10.x
      script:
        - make test-integration
    - name: 'Integration Tests Linux 1.11'
      go:
        - 1.11.x
      script:
        - make test-integration
    - name: 'Integration Tests Linux 1.12'
      go:
        - 1.12.x
      script:
        - make test-integration

